repos:
  - repo: https://github.com/psf/black
    rev: 21.5b1
    hooks:
      - id: black
        args:
          - --diff
          - --check

  - repo: https://github.com/pycqa/isort
    rev: 5.10.0
    hooks:
      - id: isort
        args:
          - --diff
          - --check-only

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
