[tool.poetry]
name = "pdf-bot"
version = "1.0.0"
description = "Telegram bot that can do a lot of things related to PDF files."
authors = ["zeshuaro <zeshuaro@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
Babel = "2.11.0"
google-cloud-datastore = "2.10.0"
humanize = "4.4.0"
img2pdf = "0.4.4"
ocrmypdf = "14.0.1"
pdf2image = "1.16.0"
"pdfminer.six" = "20221105"
python-dotenv = "0.21.0"
python-telegram-bot = "13.14"
Pillow = "9.3.0"
PyPDF2 = "2.11.2"
requests = "2.28.1"
slack-sdk = "3.19.4"
weasyprint = "57.1"
noteshrink = { git = "https://github.com/zeshuaro/noteshrink" }
pdf-diff = { git = "https://github.com/zeshuaro/pdf-diff" }
langdetect = "1.0.9"
loguru = "0.6.0"
sentry-sdk = "1.11.1"
dependency-injector = "4.40.0"
pdfCropMargins = "1.0.9"

[tool.poetry.group.dev.dependencies]
black = "22.10.0"
isort = "5.10.1"
pylint = "2.15.6"
pytest = "7.2.0"
pytest-cov = "4.0.0"
pre-commit = "2.20.0"
mypy = "0.991"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.pylint.master]
extension-pkg-allow-list = ["dependency_injector"]

[tool.pylint.message-control]
disable = [
    "consider-using-f-string",
    "consider-using-with",
    "duplicate-code",
    "invalid-name",
    "missing-class-docstring",
    "missing-function-docstring",
    "missing-module-docstring",
    "too-few-public-methods",
    "too-many-arguments",
    "too-many-branches",
    "too-many-instance-attributes",
    "too-many-locals",
    "too-many-return-statements",
    "unspecified-encoding",
]

[tool.pylint.tests]
disable = ["attribute-defined-outside-init", "too-many-public-methods"]

[tool.mypy]
warn_unused_configs = true
warn_redundant_casts = true

show_error_codes = true
disable_error_code = [
    'arg-type',
    'attr-defined',
    'union-attr',
    'operator',
    'assignment',
    'return-value',
    'import',
    'misc',
    'index',
    'str-bytes-safe',
    'var-annotated',
    'dict-item',
]


[[tool.mypy.overrides]]
module = [
    'tests.*',
    "pdf_bot.account.*",
    'pdf_bot.language_new.*',
    'pdf_bot.telegram_internal.*',
    'pdf_bot.cli.*',
    'pdf_bot.crop.*',
    'pdf_bot.file_processor.*',
    'pdf_bot.file_task.*',
    'pdf_bot.io.*',
    'pdf_bot.merge.*',
    'pdf_bot.pdf.*',
    'pdf_bot.text.*',
    'pdf_bot.watermark.*',
    'pdf_bot.command.*',
    'pdf_bot.pdf_processor.*',
    'pdf_bot.image.*',
]
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true

warn_unused_ignores = true
warn_no_return = true
warn_return_any = true
warn_unreachable = true
