[tool.poetry]
name = "pdf-bot"
version = "1.0.0"
description = "Telegram bot that can do a lot of things related to PDF files."
authors = ["zeshuaro <zeshuaro@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
Babel = "2.10.1"
Flask = "2.1.2"
google-cloud-datastore = "2.5.1"
gunicorn = "20.1.0"
humanize = "4.1.0"
img2pdf = "0.4.4"
ocrmypdf = "13.4.3"
pdfCropMargins = "1.0.5"
pdf2image = "1.16.0"
"pdfminer.six" = "20220319"
python-dotenv = "0.20.0"
python-telegram-bot = "13.11"
Pillow = "9.1.0"
PyPDF2 = "1.27.12"
requests = "2.27.1"
slack-sdk = "3.16.0"
weasyprint = "54.3"
noteshrink = {git = "https://github.com/zeshuaro/noteshrink"}
pdf-diff = {git = "https://github.com/zeshuaro/pdf-diff"}
langdetect = "1.0.9"
loguru = "0.6.0"

[tool.poetry.dev-dependencies]
black = "22.3.0"
isort = "5.10.1"
pre-commit = "2.19.0"
pylint = "2.13.8"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.pylint.message-control]
disable = [
    "consider-using-f-string",
    "consider-using-with",
    "duplicate-code",
    "invalid-name",
    "missing-class-docstring",
    "missing-function-docstring",
    "missing-module-docstring",
    "too-many-arguments",
    "too-many-branches",
    "too-many-locals",
    "too-many-return-statements",
    "unspecified-encoding",
]
