[tool.poetry]
name = "pdf-bot"
version = "1.0.0"
description = "Telegram bot that can do a lot of things related to PDF files."
authors = ["zeshuaro <zeshuaro@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
Babel = "2.10.3"
google-cloud-datastore = "2.8.0"
humanize = "4.2.3"
img2pdf = "0.4.4"
ocrmypdf = "13.6.2"
pdfCropMargins = {git = "https://github.com/zeshuaro/pdfCropMargins"}
pdf2image = "1.16.0"
"pdfminer.six" = "20220524"
python-dotenv = "0.20.0"
python-telegram-bot = "13.13"
Pillow = "9.2.0"
PyPDF2 = "2.8.1"
requests = "2.28.1"
slack-sdk = "3.18.1"
weasyprint = "56.1"
noteshrink = {git = "https://github.com/zeshuaro/noteshrink"}
pdf-diff = {git = "https://github.com/zeshuaro/pdf-diff"}
langdetect = "1.0.9"
loguru = "0.6.0"
sentry-sdk = "1.9.0"
dependency-injector = "4.39.1"

[tool.poetry.dev-dependencies]
black = "22.6.0"
isort = "5.10.1"
pylint = "2.14.5"
pytest = "7.1.2"
pytest-cov = "3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.pylint.master]
extension-pkg-allow-list = [
    "dependency_injector"
]

[tool.pylint.message-control]
disable = [
    "consider-using-f-string",
    "consider-using-with",
    "duplicate-code",
    "invalid-name",
    "missing-class-docstring",
    "missing-function-docstring",
    "missing-module-docstring",
    "too-few-public-methods",
    "too-many-arguments",
    "too-many-branches",
    "too-many-instance-attributes",
    "too-many-locals",
    "too-many-return-statements",
    "unspecified-encoding",
]
