name: Check pull request

on:
  pull_request_target:
    types:
      - opened
      - edited
      - labeled
      - unlabeled
      - synchronize

jobs:
  check:
    uses: zeshuaro/github-actions-workflows/.github/workflows/check-pull-request.yml@c7e0e2da9ee620be89ba784252459b62f1b0aa06
