name: Deploy to Production

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 5"

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    environment:
      name: Production
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      SERVICE_NAME: ${{ secrets.GCP_SERVICE_NAME }}

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Setup GCloud ⚙️
        uses: google-github-actions/setup-gcloud@master
        with:
          version: "349.0.0"
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build 🏗
        run: |-
          gcloud builds submit \
            --quiet \
            --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"

      - name: Deploy 🚀
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: ${{ env.SERVICE_NAME }}
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.SHA }}
          region: ${{ secrets.GCP_REGION }}
