name: DigitalOcean Garbage Collection

on:
  schedule:
    - cron: "0 17 * * *"

jobs:
  garbage-collection:
    name: Run Garbage Collection
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install doctl 🌊
        uses: digitalocean/action-doctl@v2.1.1
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}

      - name: Authenticate to DigitalOcean 🔐
        run: doctl registry login --expiry-seconds 600

      - name: Cleanup images 🧹
        run: |-
          doctl registry garbage-collection start --include-untagged-manifests ${{ secrets.DIGITALOCEAN_REGISTRY }}
