name: Label pull request

on:
  pull_request:
    types:
      - opened

jobs:
  label:
    uses: zeshuaro/github-actions-workflows/.github/workflows/label-pull-request.yml@138991e799dccae72b1b675048aa6ebdb5483479
