name: Snyk Scan

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "0 8 * * 3"

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Run Snyk to check for vulnerabilities 🛡️
        uses: snyk/actions/python@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif

      - name: Upload result to GitHub Code Scanning 📡
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
