name: Snyk Scan

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "0 8 * * 3"

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Setup Snyk 💻
        uses: snyk/actions/setup@master

      - name: Setup Python 🐍
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Cache Pip 💾
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies ⚙️
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run Snyk to check for vulnerabilities 🛡️
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --sarif-file-output=snyk.sarif

      - name: Upload result to GitHub Code Scanning 📡
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
